// Generated by Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import ObjectiveC;
@import Foundation;
@import CoreData;
@import SystemConfiguration;
@import Dispatch;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSCoder;

SWIFT_CLASS("_TtC14LPMessagingSDK17AgentIsTypingView")
@interface AgentIsTypingView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC14LPMessagingSDK11DataManager")
@interface DataManager : NSObject
+ (DataManager * __nonnull)instance;
@end

@class UIViewController;
@class LPUser;
@class NSData;
@protocol LPMessagingSDKNotificationDelegate;
@class UIImage;
@protocol LPMessagingSDKdelegate;

SWIFT_CLASS("_TtC14LPMessagingSDK14LPMessagingSDK")
@interface LPMessagingSDK : NSObject <UINavigationControllerDelegate>
@property (nonatomic, weak) id <LPMessagingSDKdelegate> __nullable delegate;
@property (nonatomic, copy) NSString * __nullable accountID;
@property (nonatomic) BOOL allowLogToFile;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
+ (LPMessagingSDK * __nonnull)instance;
- (void)initialize:(NSString * __nullable)encryptionKey;
- (void)showConversation:(NSString * __nonnull)accountID authenticationCode:(NSString * __nullable)authenticationCode containerViewController:(UIViewController * __nullable)containerViewController;
- (void)removeConversation:(NSString * __nonnull)accountID;
- (void)toggleChatActions:(NSString * __nonnull)accountID;
- (NSString * __nonnull)getLogsPath;
- (NSString * __nonnull)getLogsFilename;
- (void)setUserProfile:(LPUser * __nonnull)user accountID:(NSString * __nonnull)accountID;
- (void)handlePush:(NSDictionary * __nonnull)userInfo;
- (void)registerPushNotificationsWithToken:(NSData * __nonnull)token notificationDelegate:(id <LPMessagingSDKNotificationDelegate> __nullable)notificationDelegate;
- (void)setCustomButton:(UIImage * __nullable)image;
@end

@class LPNotification;

SWIFT_PROTOCOL("_TtP14LPMessagingSDK34LPMessagingSDKNotificationDelegate_")
@protocol LPMessagingSDKNotificationDelegate
@optional
- (void)LPMessagingSDKNotificationWithDidReceivePushNotification:(LPNotification * __nonnull)notification;
- (BOOL)LPMessagingSDKNotificationWithShouldShowPushNotification:(LPNotification * __nonnull)notification;
- (UIView * __nonnull)LPMessagingSDKNotificationWithCustomLocalPushNotificationView:(LPNotification * __nonnull)notification;
- (void)LPMessagingSDKNotificationWithLocalNotificationTapped:(LPNotification * __nonnull)notification;
@end

@class NSError;

SWIFT_PROTOCOL("_TtP14LPMessagingSDK22LPMessagingSDKdelegate_")
@protocol LPMessagingSDKdelegate
@optional
- (void)LPMessagingSDKCustomButtonTapped;
- (void)LPMessagingSDKAgentDetails:(LPUser * __nonnull)agent;
- (void)LPMessagingSDKActionsMenuToggled:(BOOL)toggled;
- (void)LPMessagingSDKHasConnectionError:(NSString * __nullable)error;
- (void)LPMessagingSDKDidReceiveEventLog:(NSString * __nonnull)eventLog;
@required
- (void)LPMessagingSDKObseleteVersion:(NSError * __nonnull)error;
- (void)LPMessagingSDKAuthenticationFailed:(NSError * __nonnull)error;
- (void)LPMessagingSDKDataEncryptionFailed:(NSError * __nonnull)error;
@end


SWIFT_CLASS("_TtC14LPMessagingSDK14LPNotification")
@interface LPNotification : NSObject
@property (nonatomic, copy) NSString * __nonnull text;
@property (nonatomic, strong) LPUser * __nonnull user;
@property (nonatomic, readonly, copy) NSString * __nonnull toString;
@end


SWIFT_CLASS("_TtC14LPMessagingSDK6LPUser")
@interface LPUser : NSObject
@property (nonatomic, copy) NSString * __nullable firstName;
@property (nonatomic, copy) NSString * __nullable lastName;
@property (nonatomic, copy) NSString * __nullable profileImageURL;
@property (nonatomic, copy) NSString * __nullable phoneNumber;
- (nonnull instancetype)initWithFirstName:(NSString * __nullable)firstName lastName:(NSString * __nullable)lastName profileImageURL:(NSString * __nullable)profileImageURL phoneNumber:(NSString * __nullable)phoneNumber OBJC_DESIGNATED_INITIALIZER;
@end

@class NSDate;

SWIFT_CLASS("_TtC14LPMessagingSDK8LogEvent")
@interface LogEvent : NSObject
@property (nonatomic, readonly, copy) NSString * __nonnull className;
@property (nonatomic, readonly, copy) NSString * __nonnull functionName;
@property (nonatomic, readonly, copy) NSString * __nonnull message;
@property (nonatomic, readonly, strong) NSDate * __nonnull timestamp;
@end


@interface NSDate (SWIFT_EXTENSION(LPMessagingSDK))
@end


@interface NSDate (SWIFT_EXTENSION(LPMessagingSDK))
@end


@interface NSManagedObject (SWIFT_EXTENSION(LPMessagingSDK))
@end


@interface NSOperationQueue (SWIFT_EXTENSION(LPMessagingSDK))
@end


@interface NSOutputStream (SWIFT_EXTENSION(LPMessagingSDK))
@end

@class NSNotificationCenter;

SWIFT_CLASS("_TtC14LPMessagingSDK12Reachability")
@interface Reachability : NSObject
@property (nonatomic, copy) void (^ __nullable whenReachable)(Reachability * __nonnull);
@property (nonatomic, copy) void (^ __nullable whenUnreachable)(Reachability * __nonnull);
@property (nonatomic) BOOL reachableOnWWAN;
@property (nonatomic, strong) NSNotificationCenter * __nonnull notificationCenter;
@property (nonatomic, readonly, copy) NSString * __nonnull currentReachabilityString;
- (nullable instancetype)initWithReachabilityRef:(SCNetworkReachabilityRef __nullable)reachabilityRef OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithHostname:(NSString * __nonnull)hostname;
+ (Reachability * __nullable)reachabilityForInternetConnection;
+ (Reachability * __nullable)reachabilityForLocalWiFi;
- (BOOL)startNotifier;
- (void)stopNotifier;
- (BOOL)isReachable;
- (BOOL)isReachableViaWWAN;
- (BOOL)isReachableViaWiFi;
@property (nonatomic, readonly, copy) NSString * __nonnull description;
@end


@interface UIColor (SWIFT_EXTENSION(LPMessagingSDK))
- (nonnull instancetype)initWithRgba:(NSString * __nonnull)rgba;
@end


@interface UIImageView (SWIFT_EXTENSION(LPMessagingSDK))
@end


@interface UITableViewCell (SWIFT_EXTENSION(LPMessagingSDK))
@end


@interface UIView (SWIFT_EXTENSION(LPMessagingSDK))
@end

@class NSURL;
@class NSStream;

SWIFT_CLASS("_TtC14LPMessagingSDK9WebSocket")
@interface WebSocket : NSObject <NSStreamDelegate>
@property (nonatomic, strong) dispatch_queue_t __null_unspecified queue;
@property (nonatomic, copy) void (^ __nullable onConnect)(void);
@property (nonatomic, copy) void (^ __nullable onDisconnect)(NSError * __nullable);
@property (nonatomic, copy) void (^ __nullable onText)(NSString * __nonnull);
@property (nonatomic, copy) void (^ __nullable onData)(NSData * __nonnull);
@property (nonatomic, copy) void (^ __nullable onPong)(void);
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * __nonnull headers;
@property (nonatomic) BOOL voipEnabled;
@property (nonatomic) BOOL selfSignedSSL;
@property (nonatomic, readonly) BOOL isConnected;
- (nonnull instancetype)initWithUrl:(NSURL * __nonnull)url OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithUrl:(NSURL * __nonnull)url protocols:(NSArray<NSString *> * __nonnull)protocols;

/// disconnect from the websocket server
- (void)disconnect;

/// write a string to the websocket. This sends it as a text frame.
- (void)writeString:(NSString * __nonnull)str;

/// write binary data to the websocket. This sends it as a binary frame.
- (void)writeData:(NSData * __nonnull)data;
- (void)writePing:(NSData * __nonnull)data;
- (void)stream:(NSStream * __nonnull)aStream handleEvent:(NSStreamEvent)eventCode;
@end

#pragma clang diagnostic pop
